=== api-evangelist/whatsapp/json-schema/whatsapp-business-management-api-whats-app-business-account-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/whatsapp/refs/heads/main/json-schema/whatsapp-business-management-api-whats-app-business-account-schema.json",
  "title": "WhatsAppBusinessAccount",
  "description": "WhatsAppBusinessAccount from WhatsApp API",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "example": "wamid.abc123"
    },
    "name": {
      "type": "string",
      "example": "Example Business"
    },
    "currency": {
      "type": "string",
      "example": "example_value"
    },
    "timezone_id": {
      "type": "string",
      "example": "wamid.abc123"
    },
    "country": {
      "type": "string",
      "example": "example_value"
    },
    "status": {
      "type": "string",
      "enum": [
        "ACTIVE",
        "INACTIVE"
      ],
      "example": "ACTIVE"
    },
    "business_verification_status": {
      "type": "string",
      "example": "sent"
    },
    "message_template_namespace": {
      "type": "string",
      "example": "Example Business"
    },
    "owner_business": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "primary_funding_id": {
      "type": "string",
      "example": "wamid.abc123"
    },
    "purchase_order_number": {
      "type": "string",
      "example": "example_value"
    }
  }
}

=== api-evangelist/whatsapp/examples/whatsapp-business-management-api-whats-app-business-account-example.json
{
  "id": "wamid.abc123",
  "name": "Example Business",
  "currency": "example_value",
  "timezone_id": "wamid.abc123",
  "country": "example_value",
  "status": "ACTIVE",
  "business_verification_status": "sent",
  "message_template_namespace": "Example Business",
  "owner_business": {
    "id": "wamid.abc123",
    "name": "Example Business"
  },
  "primary_funding_id": "wamid.abc123"
}
